
FROM ghcr.io/home-assistant/aarch64-base:3.21

# 安装依赖
RUN apk add --no-cache  gettext nginx

# 创建工作目录
WORKDIR /app

# 只复制构建后的文件
COPY build /app


# 添加默认配置文件
COPY public/config/userConfig.json.example /app/config/userConfig.json

COPY nginx.conf /etc/nginx/conf.d/default.conf


# 复制启动脚本
COPY run.sh /
RUN chmod a+x /run.sh

# 暴露端口
EXPOSE 5123

CMD [ "/run.sh" ]