
FROM ghcr.io/hassio-addons/base:17.1.0

# 安装依赖
RUN apk add --no-cache  gettext nginx

# 创建工作目录
WORKDIR /app

# 只复制构建后的文件
COPY build /app

RUN rm /app/config/userConfig.json
RUN rm /app/env.js



COPY nginx.conf /etc/nginx/http.d/default.conf


# 复制启动脚本
COPY run.sh /
RUN chmod a+x /run.sh

# 暴露端口
EXPOSE 5123

CMD [ "/run.sh" ]